# Generated by Django 5.1.4 on 2025-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_threadpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
