# Generated by Django 5.1.4 on 2025-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='New Blog', max_length=100),
        ),
    ]
